### ISSUE TITLE
Integrating Points to Commerce

### ISSUE THREAD

**Issue by AntonioXIII** [tributemedia/tpc_userpoints_ext#2]
Make userpoints a currency for Commerce.

The commerce_loyalty_points module might prove to be a useful example of a module implementing its own currency type and a balanced based currency.

Currencies are defined in the price sub module of commerce.

**Denomination should stay in dollar values, price should be the thing in point value**

Requirements
- Attach a userpoints price to products instead of dollars
- Cart should show total price in points 
- Checkout should show total price in points
- Upon checkout, points should be deducted.

**Comment by AntonioXIII** [comment]
Use the payment_example module in commerce to help provide a template for what should be done. In short, we need to rely on the payment module, which provides a good foundation for defining payment types.

Using the example in payment_example, make a class that implements the OnsitePaymentGatewayBase class from Commerce, and override buildConfigurationForm and defaultForms to do nothing, since this should not be configurable.

Then use the example in payment_example to define functionality that should happen for payment processing.

**Comment by AntonioXIII** [comment]
12/24 morning progress:

Implemented a payment gateway and it registers just fine. On checkout it fails though because checkout calls createPaymentMethod which has a second parameter that expects payment details, though none are given. This should be fixed by taking out the second parameter, or giving it a default value.

**Comment by AntonioXIII** [comment]
IMPORTANT: Review separate email for details and requests for feedback.

This is now ready for review.

**Comment by skenley** [comment]
I think we should be able to eliminate the "Payment Information" pane but the "Order Information" pane needs some work. If it doesn't make sense to eliminate the "Payment Information" pane, I'm ok with that as well. If you walk through a checkout on the Dev environment you will see that the "Order Information" pane includes the "Resident Information" section to include the user's home property and unit number. This is very important information that needs to be included in the order. I'm not sure if this is something that needs to be configured in the interface, or if it was affected by the install of the Payment module but the information must be a part of the order.

I think the TUP needs to be removed from the "customer" facing displays at least. It would be preferable to remove the TUP and add a suffix that says "points" or something of that nature. So, on the product pages, under the image it would say "1000 points" rather than "TUP1000."

**Comment by skenley** [comment]
One more thing I noticed was that the order status is gone. The order workflow needs to be when an item is added to the cart the status is "cart." When the checkout is complete, the status should be "fulfillment." When the order has been fulfilled the status should be "complete."

**Comment by AntonioXIII** [comment]
Notes from call with Steve:

The TUP currency symbol still needs fixed, but the other two items (order status and resident information in checkout) should be addressed by the latest round of config changes in dev that haven't been applied to the multidev I've been working on. Steve is going to spin up a new multidev that will have the latest code from dev and I'll test the module on that.

Things to do before installing the module on the new multidev:

- Change the display of TUP prices to not include the currency symbol, but rather something like '100 points'.
- Update module dependencies to require commerce, commerce_payment and views bulk operation module.
- Include custom currency in install config, along with the vbo view.

**Comment by AntonioXIII** [comment]
Overwriting the TUP from the customer facing windows turned out to be a real pain. However, I have a working solution, though it requires some manual configuration:

1. In the Cart page and block views, you'll have to configure each field that is displaying price to use the newly created Points field formatter (this will not apply to the subtotal and total area, more on that in the second point).
2. The total summary area is imported into the cart page view by using a global field definition (which is in the footer by default). This will need to be swapped out with the Order total TPC field, which does the same thing as the other but displays 'points' instead of the currency code 'TUP'.
3. On each product variation type made, you'll need to change on the view display the formatter of the price field to the 'Points' formatter.

Other than that, all feedback has been implemented from above. Since no multidev currently exists and I cannot afford to wait, I am going to test this on the dev environment (after creating a restore first, of course). If everything looks kosher I'll mark this as ready for review again.

**Comment by AntonioXIII** [comment]
Due to a composer error I have to install transaction and userpoints through SFTP upload. I will put them in the custom modules directory for now.

**Comment by AntonioXIII** [comment]
This is good to go and ready for review again, see other e-mail sent to Steve for details.

**Comment by AntonioXIII** [comment]
Regarding billing information, I found that the payment module disables the billing information checkout pane in its .module file. I have commented out this line for now as a quick resolution to this problem as we need the extra time for points integration into the commerce module, but this should have a better resolution and the line will have to be commented out every time commerce is updated.

**Comment by AntonioXIII** [comment]
Resolving for now, I have created the follow up task to make sure a better solution gets implemented regarding the billing information portion when there is time.
