### ISSUE TITLE
Integrate TPC Points to Questionnaire

### ISSUE THREAD

**Issue by AntonioXIII** [tributemedia/tpc_userpoints_ext#7]
Integrate the points functionality with the questionnaire module. This should involve:

- Adding a points field to a quiz so that an admin can decide how many points get awarded to a user when they pass the quiz.
- Respond to a FirstTimePass event (to be made in the questionnaire module) to award points to the user passing the quiz (this will require a separate transaction operation to be made, similar to the commerce operation).

**Comment by AntonioXIII** [comment]
Questionnaire module has been successfully installed on the new multidev, and a test shows that things appear to be working as they were on the quiz multidev. Next step is point 1 on the first comment above.

**Comment by AntonioXIII** [comment]
@skenley Just a heads up: Don had some styles on the quiz multidev that were put into a theme which made the checkbox text on the same line as the checkbox. Currently that is not in place since those styles were placed in a theme CSS. I feel that this is where the style belongs as this isn't an issue with module styling but rather the styling of the site itself. Just an FYI in case you come across it during any test you might do of questionnaire on the new-points multidev.

**Comment by AntonioXIII** [comment]
This is now pretty much done; When a user first passes a quiz they get awarded the amount of points specified in the quiz node. However, I am going to see if I can mess with the transaction operation template to pass in the name of the quiz so one can see what quiz the user was awarded points for passing.

**Comment by skenley** [comment]
Just a thought. You might consider passing the node id rather than the
title of the quiz. That way you'll have access to all data from the quiz.
May not need it now but it could come in handy down the road.

Steve Kenley
Senior Developer | Tribute Media
208.489.0062

**Comment by AntonioXIII** [comment]
@skenley Good idea! I had to add a field to pull it off (and adjust creation logic so that the field would be populated when passing a quiz), but the description template now prints the name of the quiz, and all other quiz information is available as tokens in the template. 

This is pretty much good to go now! There's a follow up task I want to do (to improve how I'm doing things), but I'm going to focus on the manager form first.
